# Generated by Django 5.2.5 on 2025-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
