# Generated by Django 4.2.24 on 2025-09-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_appointment_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
