# Generated by Django 4.2.24 on 2025-09-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_remove_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctorId',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patientId',
        ),
    ]
