# Generated by Django 5.2.5 on 2025-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_rename_doctor_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
