# Generated by Django 5.2.5 on 2025-10-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_prescription_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientId',
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
    ]
